### ISSUE TITLE
binary_sensor.cloudflared_running ?

### ISSUE THREAD

**Issue by johntdyer** [bacco007/HomeAssistantConfig#85]
Its not clear to my where `binary_sensor.cloudflared_running` comes from... I searched your config for various iterations of it to see how you're defining it but cant find anything...

```
platform: template
switches:
  addon_cloudflared:
    friendly_name: "[Addon] Cloudflared"
    unique_id: addon_cloudflared
    entity_picture_template: >
      {{state_attr('update.cloudflared_update', 'entity_picture')}}
    value_template: >
      {{is_state('binary_sensor.cloudflared_running', 'on')}}
    availability_template: >
      {{is_state('binary_sensor.cloudflared_running', 'on')}}
    turn_on:
      service: hassio.addon_start
      data:
        addon: 9074a9fa_cloudflared
    turn_off:
      service: hassio.addon_stop
      data:
        addon: 9074a9fa_cloudflared
```

Thanks again !
